x=lambda rno,name,m1,m2,m3:(m1+m2+m3)
rno=int(input("Enter roll number : "))
name=input("Enter name : ")
m1=int(input("Enter marks : "))
m2=int(input("Enter marks : "))
m3=int(input("Enter marks : "))
per=(m1+m2+m3)/3
total=x(rno,name,m1,m2,m3)
print("Roll No. : ",rno)
print("Name : ",name)
print("M1 : ",m1)
print("M2 : ",m2)
print("M3 : ",m3)
print("Grand Total : ",total)
print("Percentage : ",per)
