a=45
b=6
sum=a+b
sub=a-b
multi=a*b
div=a/b
rem=a%b
print("a=",a)
print("b=",b)
print(" Addition = ",sum)
print(" Subtraction = ",sub)
print(" Muliplication = ",multi)
print(" Division = ",div)
print(" Remainder = ",rem)
