a=int (input("Enter any number : "))
b=int(input(" Enter any number : "))
sum=a+b
sub=a-b
multi=a*b
div=a/b
rem=a%b
print(" Addition = ",sum)
print(" Subtraction = ",sub)
print(" Muliplication = ",multi)
print(" Division = ",div)
print(" Reaminder = ",rem)
