rno=1
Name="Nalini"
M1=23
M2=45
M3=67
total=M1+M2+M3
per=total/3
print(" Roll no. = ",rno)
print(" Name = ",Name)
print(" M1 = ",M1)
print(" M2 = ",M2)
print(" M3 = ",M3)
print(" Total = ",total)
print(" Percentage = ",per)
